### PR TITLE
[foxy backport] Add pytest.ini so local tests don't display warning (#48)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #48 to Foxy.

This should help resolve one of the outstanding failures in ros2/ci#503

### CODE REVIEW

**Comment by sloretz** [comment]
Do you know why the PR job failed? Seems like it's related to a JUnit file

```
15:45:58 INFO: Processing GoogleTest-1.8
15:45:58 INFO: [GoogleTest-1.8] - 11 test report file(s) were found with the pattern 'ws/test_results/**/*.xml' relative to '/home/jenkins-agent/workspace/Fpr__resource_retriever__ubuntu_focal_amd64' for the testing framework 'GoogleTest-1.8'.
15:45:58 WARNING: The converted file for the input file '/home/jenkins-agent/workspace/Fpr__resource_retriever__ubuntu_focal_amd64/ws/test_results/resource_retriever/Testing/20200813-2245/Test.xml' doesnt match the JUnit format.
15:45:58 WARNING: At line 2 of file:/home/jenkins-agent/workspace/Fpr__resource_retriever__ubuntu_focal_amd64/generatedJUnitFiles/b1876658-7355-4bae-9c52-33779c248568/GoogleTest/TEST-682b4afd-59ad-4880-a948-cea22422544d.xml:Premature end of file.
15:45:58 WARNING: Technical validation:Premature end of file.
15:45:58 ERROR: Premature end of file.
15:45:58 ERROR: Premature end of file.
15:45:58 ERROR: Step ‘Publish xUnit test result report’ failed: The converted file for the result file '/home/jenkins-agent/workspace/Fpr__resource_retriever__ubuntu_focal_amd64/ws/test_results/resource_retriever/Testing/20200813-2245/Test.xml' (during conversion process for the metric 'GoogleTest') is not valid. The report file has been skipped.
15:45:58 Setting status of 1081a1aba001532a36244365a98cf48e2900ca67 to FAILURE with url http://build.ros2.org/job/Fpr__resource_retriever__ubuntu_focal_amd64/5/ and message: 'Build finished. '
15:45:58 Using context: Fpr__resource_retriever__ubuntu_focal_amd64
15:45:59 Finished: FAILURE
```

**Comment by jacobperron** [comment]
I think it was an infrastructure issue resolved in https://github.com/ros-infrastructure/ros_buildfarm/pull/828.

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
CI for this PR and several other similar backports can be found here: https://github.com/ros2/ci/pull/503#issuecomment-673751744

**Review by clalancette — APPROVED** [review]

**Pull request merged**
