### PR TITLE
Update curl reference from 7.57 to 7.58

### PR DESCRIPTION
**Pull request by nbbrooks**
Pulls in curl fix curl/curl#2154 to fix resource retrieval in Windows

### CODE REVIEW

**Comment by nbbrooks** [comment]
Windows Rviz error message with curl version <7.58 for retrieving a resource such as
`package://my_package/meshes/actuator.stl`

`[rviz2.EXE-3] [ERROR] [rviz2]: Error retrieving file [file://C:\dev\ros2_example_ws\install\my_package/share/my_package/meshes/actuator.stl]: Invalid file://hostname/, expected localhost or 127.0.0.1 or none`

**Review by wjwwood — APPROVED** [review]
lgtm, thanks!

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9226/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4915/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7530/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9145/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/25/)

**Comment by wjwwood** [comment]
macOS is having a bad day on our CI farm. I'll merge without and follow up if something shows up on nightly, but I think we don't use the vendor on macOS.

**Pull request merged**
