### PR TITLE
Add c++11 flag

### LINKED ISSUE #3: Compiler warning on kinetic
Complains about [retriever.h:81](https://github.com/ros/resource_retriever/blob/kinetic-devel/include/resource_retriever/retriever.h#L81)

```
defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
```
- http://build.ros.org/view/Kdev/job/Kdev__resource_retriever__ubuntu_xenial_amd64/2/warnings17Result/

Downstream packages have the same warning:
- http://build.ros.org/view/Kdev/job/Kdev__robot_model__ubuntu_xenial_amd64/6/warnings17Result/

### PR DESCRIPTION
**Pull request by DLu**
Fixes #3

### CODE REVIEW

**Comment by jackieokay** [comment]
Thanks, David!

As a side note, you can put the CMAKE_CXX_FLAGS inside of the quotes, e.g. `set(CMAKE_CXX_FLAGS"${CMAKE_CXX_FLAGS} -std=c++11")`. But both will work.

**Comment by scpeters** [comment]
Will this export the flags? Downstream packages have the warning as well.

**Comment by DLu** [comment]
I only confirmed that it removed the warning in this package. Sorry.

**Comment by scpeters** [comment]
No problem, it will be obvious if it's still there

**Pull request merged**
