### PR TITLE
Update curl reference from 7.57 to 7.58

### PR DESCRIPTION
**Pull request by nbbrooks**
Pulls in this curl fix https://github.com/curl/curl/pull/2154

Fixes resource retrieval in Windows

### CODE REVIEW

**Comment by nbbrooks** [comment]
Curl 7.57 has a bug which results in resource retrieval such as
`package://my_package/meshes/actuator.stl`

```
Failing to load with
[rviz2.EXE-3] [ERROR] [rviz2]: Error retrieving file [file://C:\dev\ros2_example_ws\install\my_package/share/my_package/meshes/actuator.stl]: Invalid file://hostname/, expected localhost or 127.0.0.1 or none
```

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9223/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4912/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7523/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9141/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/21/)

**Comment by wjwwood** [comment]
@nbbrooks please reopen (or update if possible) this to target the `ros2` branch. We don't take changes to distro branches directly, unless they will not be put on "`master`" (in this case `ros2`).

**Comment by wjwwood** [comment]
I think (I was confused before) that since eloquent we've moved the curl vendor to another repository...

**Comment by wjwwood** [comment]
Never mind, I was just looking at the ROS 1 branch. Sorry, it's a bit confusing. Still, targeting the `ros2` branch is the right thing to do.

**Comment by nbbrooks** [comment]
Tried retargeting but it ended up adding in some other changes. New PR here https://github.com/ros/resource_retriever/pull/36

**Pull request closed without merging**
