### PR TITLE
Make sure to export the include directory for resource_retriever.

### LINKED ISSUE #21: ROS 2: find_package doesn't populate the INCLUDE_DIRS variable as expected
In RViz2, we're using resource_retriever as a dependency. When doing a `find_package(resource_retriever REQUIRED)` I would have expected the variable `resource_retriever_INCLUDE_DIRS` to contain the path to the include files of resource retriever and its dependencies.

However, it only contains the paths to the includes of its dependencies (in an isolated build, e.g. ` <path_to_ros2>/install_isolated/ament_index_cpp/include;/usr/include/x86_64-linux-gnu`). Is this expected behaviour? If yes, how do I get the correct include paths for building static and object libraries? 

Background: When building all rviz2 libraries dynamically, everything works fine (I don't quite understand how, but `ament_export_interfaces` seems to play a role), but in order to have tests for its default plugins, I want to build a static library of `rviz_default_plugins` as well - at that point, ament can't find the correct includes of `resource_retriever` anymore.

### PR DESCRIPTION
**Pull request by clalancette**
Otherwise, it can't properly be used as a library.

fixes #21 

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4057/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1141/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3370/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4135/)

**Comment by mikaelarguedas** [comment]
Can you please export the package libraries, interfaces and the include directories before the dependencies? (c.f. [ongoing set of PRs](https://github.com/ros2/ros2/issues/468) for fixing the order of exports)

**Comment by clalancette** [comment]
> Can you please export the package libraries, interfaces and the include directories before the dependencies? (c.f. ongoing set of PRs for fixing the order of exports)

Sure, the latest commit moves it around to the same order as some of the other PRs.

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Review by sloretz — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks for the reviews.  I'm fairly certain that the CI failures are unrelated to this PR (the macOS ones look like a bug in rclcpp, while the Windows one looks like a known issue: https://github.com/ros2/build_cop/issues/86).  Therefore, I'm going to merge this.

**Pull request merged**
